language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
branches:
  only:
  - develop
# command to run tests
script: 
  - ./manage.py test
  - coverage run --omit='*virtualenv*' manage.py test
after_success: coveralls
env:
  global:
    - TRAVIS_BUILD=true
